version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  send_reminder:
    docker:
      - image: cimg/node:20.9.0

    steps:
      - checkout
      - run:
          name: Install deps
          command: yarn install
      - run:
          name: Send reminder to Slack
          command: yarn send-reminder

workflows:
  version: 2

  release_cadence:
    triggers:
      - schedule:
          cron: "0 10 * * 1,2,3,4,5" # https://crontab.guru
          filters:
            branches:
              only:
                - main
    jobs:
      - send_reminder
# Uncomment the following workflow to trigger the reminder on every push, for debugging.
release_cadence_manual:
  jobs:
    - send_reminder
